filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: msg
logging.to_files: false
output.logstash:
  hosts: ["logstash:5044"]
